### PR TITLE
Hb to ltla

### LINKED ISSUE #41: Aggregate HB to LTLA
Use the geographr lookup to aggreagte from HB to LTLA.

**Healthy Lives**

- [x] Sexual Health

**Health People**

- [ ] #42 - data unavailable
- [x] Diabetes
- [x] #43
- [x] #44
- [x] Rheumatoid arthritis
- [x] #45
- [x] #46

**Health Places**

- [x] Patients offered acceptable GP practice appointments

### PR DESCRIPTION
**Pull request by MikeJohnPage**
Closes #41 

Note there is missing data for several of the indicators that were supposed to be included as part of the aggregations from HB to LTLA. Please review #43 #44 #45 and #46 and let me know what you would like to do.

### CODE REVIEW

**Review by matthewgthomas — CHANGES_REQUESTED** [review]
[ONS's approach](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandwellbeing/methodologies/healthindexmethodsanddevelopment2015to2019#imputation-of-missing-data-coin-step-3-) to missing data is: "if a value was missing for an LTLA for all years, we imputed the median for its region."

Scotland doesn't have official regions for doing a similar kind of imputation. Instead, can you assign the median value for Scotland to LTLAs missing data?

Please try running a sensitivity analysis to see what difference it makes using imputed values vs leaving missing values as NA.

**Comment by MikeJohnPage** [comment]
@karoliskoncevicius Please can you action this?

**Comment by karoliskoncevicius** [comment]
Hey @matthewgthomas, currently I am imputing the data using the mean instead of median so wanted to hear your thoughts and feedback about it. Here are some nice properties about the mean in the pipeline that you have now:

1. After z-score transform the mean of each indicator is 0, so the procedure is simply to replace the NA values with 0. If instead we impute the mean before z-score transform the imputed values would turn to 0 after subtracting the mean, leading to the same final score. This is not preserved with the median, as median imputation would affect the mean that is being subtracted for z-score transform.

2. Imputing the mean makes the missing values uninformative. Since after z-score transform imputed means are 0 - it leads to them not affecting the final scores (addition of 0, weighted or unweighted).

3. The imputation with the mean also works well with PCA rotation, as it again makes the imputed scores uninformative when looking for directions of max variance. The median might shift the final rotation a tiny bit again slightly affecting the scores of all other regions. P.S. sensitivity analysis could not be done with PCA, as PCA cannot handle (skip) missing values.

In my opinion the median would make more sense if we used robust z-scores (calculated as (x - median) / MAD), instead of (x - mean) / SD). I am of course happy to try median imputation, but wanted to share my thoughts for your feedback.

**Comment by matthewgthomas** [comment]
Hey @karoliskoncevicius - that all makes sense. I was originally thinking we should follow the ONS's approach of imputing missing data before we transform/normalise and combine the indicators - but I really like your approach of using a mean of 0. That means we can show users which data is missing, but still produce a meaningful composite index. No further changes required. I'll merge this PR.

**Pull request merged**
