### PR TITLE
added pca+varimax based index calculation and the result

### PR DESCRIPTION
**Pull request by karoliskoncevicius**
Index calculation weighted by PCA.

- Used the following document as a guide: https://www.oecd-ilibrary.org/docserver/9789264043466-en.pdf?expires=1732447217&id=id&accname=guest&checksum=C9FB3C0E94A6DE6D49C811382692119B
- Missing values imputed with the indicator means
- Principal components were calculated based on all 3 domains combined (lives, people, and places)
- Weights calculated based on varimax rotation

### CODE REVIEW

**Comment by matthewgthomas** [comment]
@karoliskoncevicius - we would like separate PCAs to be run to calculate individual sub-domains, rather than one PCA on all indicators at the same time.

Here is a list of which indicators make up which sub-domains: https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandwellbeing/methodologies/healthindexindicatorsanddefinitions

Once sub-domains have been calculated using PCAs, can you combine them into the three domains using arithmetic means with equal weights. Finally, combine the three domains into an overall Health Index score using arithmetic means with equal weights.

**Comment by karoliskoncevicius** [comment]
@matthewgthomas yup it makes sense! I already discussed this with Mike. It also would get rid of the issue of data having more variables than observations (regions). Will implement it sometime during the week and update the pull request.

**Comment by karoliskoncevicius** [comment]
@matthewgthomas Adjusted index build to do PCA weighting for lives, people, and places separately. As a sanity check I looked at correlations between location ranks obtained via PCA-varimax weighteed and unweighted methods (see picture).

Screenshot 5

Seems like they agree quite well. The biggest difference in Scotland data is seen in the "places" domain. But I am not sure why. Maybe the correlation structure between indicators there is different (i.e. more highly correlated indicators)

**Comment by karoliskoncevicius** [comment]
@matthewgthomas 

One thing I am not too sure about is the final combination of the 3 domains into the final score. I followed the example I found in the functions used by various index repositories. And there there is a function named calculate_composite_score(): https://github.com/humaniverse/health-index-wales/blob/main/R/utils.R#L413 . What it does is it takes the ranks of all 3 domains, transforms them by division, and then sums them up. I am not quite sure why it's done this way instead of, say, simply summing up the z-scores (and not ranks) of the 3 domains.

For now I followed the procedure that was being done. But just making a note to double check if it makes sense with you.

**Comment by MikeJohnPage** [comment]
@matthewgthomas Please review changes and advise as necessary.

**Comment by matthewgthomas** [comment]
Thanks @karoliskoncevicius. We need the **sub-domains** to be calculated by PCA, not the domains. For example, the 'Mortality' sub-domain (which is part of the 'Healthy People' domain) should be calculated as a PCA of the 'avoidable mortality', 'infant mortality', 'life expectancy' and 'mortality from all causes' indicators.

Here's the list of the domains, sub-domains, the indicators which form each sub-domain: https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandwellbeing/methodologies/healthindexindicatorsanddefinitions

Once all the sub-domains have been calculated this way, let's calculate the domain scores (Healthy People, Healthy Lives, Healthy Places) as a sum of z-scores. Then calculate the overall Health Index score as the sum of the three domain z-scores.

**Comment by MikeJohnPage** [comment]
This is my fault, I forgot there was subdomains. We will fix now. Thanks!

**Comment by karoliskoncevicius** [comment]
Hello @matthewgthomas - added a PCA version that is done at the sub-domain level, and not the domain level.

There are a few details that seem to be important:

1. I noticed quite a few discrepancies between the sub-domain info in the document and the collected data. In particular - a lot of data are listed under one domain in our repository, but in a different domain in the document. For example "child_poverty", "job_training", "unemployment", "workplace_safety" are all in "PLACES" in the document, but in "LIVES" in the repository. There are more like that (I left NOTE: comments in the build-index-pca.R script).

2. Several indicators that are listed under sub domains in the document are missing from the repository. A few examples "self-harm", "frailty", "acceptable_gp_appointments", "cariovascular_health", "sexual_health", among others.

3. Feels to me that the job of PCA is to find these sub-domains empirically from the data. Now that we are manually defining them, the PCA step might not be that helpful. Indeed, the indicators are almost manually weighted according how many of them are within each sub domain. Some sub-domains are composed of only one indicator, and those will have higher weights, compared to indicators from a sub-domain containing many. I would like to spend a bit of time to double-check that we are still on the right track. Do you think this would be worthwhile?

**Comment by MikeJohnPage** [comment]
@karoliskoncevicius for point 2., this is to be expected. We stripped these indicators as there wasn't enough data. So you can leave these out of the analyses.

@matthewgthomas can comment on points 1. and 3. Thanks!

**Comment by MikeJohnPage** [comment]
@matthewgthomas I've just spoken to Karolis, we have agreed to leave point 3. as-is for now. Please can you respond to his first point?

**Comment by matthewgthomas** [comment]
Thanks for pointing out the discrepancies @karoliskoncevicius. I've renamed and moved those the indicators into their correct domains. I also spotted some missing/incorrect indicators being inverted and calculated in the wrong sub-domains. Everything looks good now so I'll merge and close this PR.

**Pull request merged**
